### ISSUE TITLE
Crash in flutter app when push notification is received

### ISSUE THREAD

**Issue by radubatori** [Pushwoosh/pushwoosh-flutter#5]
When the app is terminated and a push notification is received the following crash occurs and the push notification is not displayed:

```
2019-03-14 16:01:05.931 29302-29336/com.luminos.xxx I/Pushwoosh: [FcmHelper] Received message: {pw_msg=1, p=;, pri=, vib=0, title=test} from: 194832369019
2019-03-14 16:01:05.933 29302-29336/com.luminos.xxx I/Pushwoosh: [NotificationService] handleMessage: Bundle[{pw_msg=1, p=;, pri=, vib=0, title=test}]
2019-03-14 16:01:05.965 29302-29336/com.luminos.xxx E/Pushwoosh: Exception occurred
    kotlin.UninitializedPropertyAccessException: lateinit property receiveHandler has not been initialized
        at com.pushwoosh.plugin.PushwooshPlugin$Companion.getReceiveHandler(PushwooshPlugin.kt:27)
        at com.pushwoosh.plugin.PushwooshPlugin$Companion.onMessageReceived(PushwooshPlugin.kt:79)
        at com.pushwoosh.plugin.PushwooshNotificationServiceExtension.onMessageReceived(PushwooshNotificationServiceExtension.kt:33)
        at com.pushwoosh.notification.NotificationServiceExtension.a(Unknown Source:49)
        at com.pushwoosh.notification.NotificationServiceExtension.handleMessage(Unknown Source:0)
        at com.pushwoosh.PushwooshFcmHelper.onMessageReceived(Unknown Source:74)
        at com.pushwoosh.PushFcmIntentService.onMessageReceived(Unknown Source:7)
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:402)
        at com.google.firebase.iid.zzg.run(Unknown Source:26)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)
```

Details: 
- Android 8.0
- pushwoosh-flutter version: master (1.12.1 does not work with AndroidX)
- flutter 1.2.1
- everything is fine when the app is active or in the background

**Comment by wfhm** [comment]
@radubatori Checking it.

**Comment by wfhm** [comment]
@radubatori fixed in the latest release.
