### ISSUE TITLE
App crashes with release version or hot reload

### ISSUE THREAD

**Issue by lucaslombardif** [Pushwoosh/pushwoosh-flutter#58]
Hello, my app is crashing when I create a release version (apk or bundle) and also when I hot reload in debug mode.

I've actually tried all the solutions described in the documentation, but none of them worked:
 https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/flutter/known-issues-migrating-pushwoosh-flutter-plugin-to-version-2.1.0-or-higher

I also tried to upgrade and downgrade the versions, without success either.

Here's the console output when I hot reload, and the result of my flutter doctor.

Hot reload error:
<img width="773" alt="pushwoosh_error" src="https://user-images.githubusercontent.com/23706340/187792446-c5ae480b-938b-4ed3-bb01-f61acd6b6e0d.png">

Flutter doctor: 

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [versÆo 10.0.19043.1889], locale pt-BR)
    • Flutter version 3.0.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\lucflori\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = C:\Users\lucflori\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version openjdk version "11.0.11" 2021-04-20
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Ferramentas de Build do Visual Studio 2017 15.9.45)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Ferramentas de Build do Visual Studio 2017 version 15.9.28307.1831
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "11.0.11" 2021-04-20

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\lucflori\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.19043.1889]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.70

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

Versions I've Tested: 
```
2.2.7
2.2.8
2.2.9
```

**Comment by lucaslombardif** [comment]
Follow the output of adb logcat: 

```
09-01 01:25:38.658   586  1858 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=br.com.mypackagename.app/com.mypackagename.app.MainActivity bnds=[22,295][229,625]} from uid 10136
09-01 01:25:38.680   586  1451 D CoreBackPreview: Window{fc3d4e6 u0 Splash Screen br.com.mypackagename.app}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@eccc4d4, mPriority=0}
09-01 01:25:38.690   586   619 I ActivityManager: Start proc 5140:br.com.mypackagename.app/u0a157 for next-top-activity {br.com.mypackagename.app/com.mypackagename.app.MainActivity}
09-01 01:25:38.796  5140  5170 D Pushwoosh: Looking for exceptions in: /data/user/0/br.com.mypackagename.app/files
09-01 01:25:38.798  5140  5140 E AndroidRuntime: Process: br.com.mypackagename.app, PID: 5140
09-01 01:25:38.802   586  1858 W ActivityTaskManager:   Force finishing activity br.com.mypackagename.app/com.mypackagename.app.MainActivity
09-01 01:25:38.834   586  1451 I ActivityManager: Process br.com.mypackagename.app (pid 5140) has died: prcp TOP
09-01 01:25:38.850   586   682 D WindowManager: relayoutVisibleWindow: Window{fc3d4e6 u0 Splash Screen br.com.mypackagename.app EXITING} mAnimatingExit=true, mRemoveOnExit=true, mDestroying=false
09-01 01:25:39.199   586  1806 W InputManager-JNI: Input channel object 'fc3d4e6 Splash Screen br.com.mypackagename.app (client)' was disposed without first being removed with the input manager!
09-01 01:25:39.303   586   610 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{c4ac11a u0 br.com.mypackagename.app/com.mypackagename.app.MainActivity} t-1 f}}
```

**Comment by lucaslombardif** [comment]
and more: 

```
09-01 01:35:37.210   393   445 W RanchuHwc: presentDisplay display has no layers to compose, flushing client target buffer.
09-01 01:35:37.224  5704  5704 E Pushwoosh: Exception occurred
09-01 01:35:37.224  5704  5704 E Pushwoosh: java.lang.ClassNotFoundException: com.pushwoosh.plugin.PushwooshNotificationServiceExtension
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at java.lang.Class.classForName(Native Method)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at java.lang.Class.forName(Class.java:454)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at java.lang.Class.forName(Class.java:379)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at com.pushwoosh.x.c(Unknown Source:39)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at com.pushwoosh.x.<init>(Unknown Source:187)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at com.pushwoosh.r.c(Unknown Source:47)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source:11)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at android.app.ActivityThread.installProvider(ActivityThread.java:7488)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at android.os.Handler.dispatchMessage(Handler.java:106)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at android.os.Looper.loopOnce(Looper.java:201)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at android.os.Looper.loop(Looper.java:288)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at android.app.ActivityThread.main(ActivityThread.java:7898)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at java.lang.reflect.Method.invoke(Native Method)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-01 01:35:37.224  5704  5704 E Pushwoosh:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-01 01:35:37.224  5704  5704 E Pushwoosh: Caused by: java.lang.ClassNotFoundException: com.pushwoosh.plugin.PushwooshNotificationServiceExtension
09-01 01:35:37.224  5704  5704 E Pushwoosh:     ... 21 more
09-01 01:35:37.228  5704  5704 E AndroidRuntime: FATAL EXCEPTION: main
09-01 01:35:37.228  5704  5704 E AndroidRuntime: Process: br.com.allianz.mobile.saude, PID: 5704
09-01 01:35:37.228  5704  5704 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.pushwoosh.PushwooshInitProvider: java.lang.IllegalStateException: Could not find class for name: com.pushwoosh.plugin.PushwooshNotificationServiceExtension
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:7493)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7898)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-01 01:35:37.228  5704  5704 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Could not find class for name: com.pushwoosh.plugin.PushwooshNotificationServiceExtension
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at com.pushwoosh.x.c(Unknown Source:100)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at com.pushwoosh.x.<init>(Unknown Source:187)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at com.pushwoosh.r.c(Unknown Source:47)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source:11)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
09-01 01:35:37.228  5704  5704 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:7488)
```

**Comment by Techsorcist** [comment]
Hello, @lucaslombardif! For the IllegalStateException, may I ask you to check these solutions: https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/flutter#using-proguard
Please let me know if it resolves the issue!

**Comment by lucaslombardif** [comment]
Hello, @Techsorcist!  

Everything is working correctly around here, thanks!
